
# model
model_name_or_path: "Qwen/Qwen2.5-0.5B-Instruct"

# dataset
data_path: "Anthropic/hh-rlhf"
num_proc: 16
max_length: 2048

# train
epochs: 2
batch_size: 12
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
