# seed:
seed: 42

# tracker
log_with: wandb
output_dir: outputs

# dataset
num_examples: 100000


# training
accumulate_gradient_steps: 4
lr: 0.01
epochs: 5
batch_size: 32

# model
weights:
  - 1.2
  - 2.4
  - 1
gamma: 0.1

hydra:
  run:
    dir: ./
